#!/bin/bash

if [ "$SCALIENDB_RELEASE" = "1" ]; then
	echo -n -e "\033]0;CR-$1\007"
	build/Release/ScalienDB test/control/$1/scaliendb.conf
else
        echo -n -e "\033]0;CD-$1\007"
        build/Debug/ScalienDB test/control/$1/scaliendb.conf	
fi
