#!/bin/bash

DIR=$1
shift
echo -n -e "\033]0;D$DIR\007"
if [ "$SCALIENDB_RELEASE" = "1" ]; then
	build/Release/ScalienDB test/shard/$DIR/scaliendb.conf $*
else
	build/Debug/ScalienDB test/shard/$DIR/scaliendb.conf $*
fi
