#!/bin/bash

if [ $(uname) = "Darwin" ]; then
	if [ "$SCALIENDB_RELEASE" = "1" ]; then
		BIN=build/Release/ScalienDB
	else
		BIN=build/Debug/ScalienDB
	fi
else
	if [ "$SCALIENDB_RELEASE" = "1" ]; then
		BIN=build/mkrelease/scaliendb
	else
		BIN=build/mkdebug/scaliendb
	fi	
fi

DIR=$1
shift
echo -n -e "\033]0;D$DIR\007"
if [ "$1" = "-g" ]; then
	echo "r test/shard/$DIR/scaliendb.conf $*" | gdb $BIN
else
	$BIN test/shard/$DIR/scaliendb.conf $*		
fi
