#!/bin/bash

if [ $(uname) = "Darwin" ]; then
	if [ "$SCALIENDB_RELEASE" = "1" ]; then
		BIN=build/Release/ScalienDB
	else
		BIN=build/Debug/ScalienDB
	fi
else
	if [ "$SCALIENDB_RELEASE" = "1" ]; then
		BIN=build/mkrelease/scaliendb
	else
		BIN=build/mkdebug/scaliendb
	fi	
fi

kill $(ps ax| grep "$BIN test/shard/$DIR/scaliendb.conf"| grep -v grep| awk '{printf $1 " "}')
