BUILD_DIRS = \
		$(BUILD_DIR)/Application \
		$(BUILD_DIR)/Application/Client \
		$(BUILD_DIR)/Application/Client/CSharp \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClient \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClient/Properties \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientTest \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUnitTesting \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUnitTesting/Properties \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUnitTesting/TestingFramework \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUnitTestsVS \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUnitTestsVS/Properties \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUtils \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientUtils/Properties \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientWithNativeDLL \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientWithNativeDLL/Properties \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientWithNativeDLLTest \
		$(BUILD_DIR)/Application/Client/CSharp/ScalienClientWithNativeDLLTest/Properties \
		$(BUILD_DIR)/Application/Client/Java \
		$(BUILD_DIR)/Application/Client/PHP \
		$(BUILD_DIR)/Application/Client/Python \
		$(BUILD_DIR)/Application/Common \
		$(BUILD_DIR)/Application/ConfigServer \
		$(BUILD_DIR)/Application/ConfigState \
		$(BUILD_DIR)/Application/HTTP \
		$(BUILD_DIR)/Application/SDBP \
		$(BUILD_DIR)/Application/ShardServer \
		$(BUILD_DIR)/Framework \
		$(BUILD_DIR)/Framework/Clustering \
		$(BUILD_DIR)/Framework/Messaging \
		$(BUILD_DIR)/Framework/Replication \
		$(BUILD_DIR)/Framework/Replication/Paxos \
		$(BUILD_DIR)/Framework/Replication/Paxos/States \
		$(BUILD_DIR)/Framework/Replication/PaxosLease \
		$(BUILD_DIR)/Framework/Replication/PaxosLease/States \
		$(BUILD_DIR)/Framework/Replication/Quorums \
		$(BUILD_DIR)/Framework/Replication/ReplicatedLog \
		$(BUILD_DIR)/Framework/Storage \
		$(BUILD_DIR)/Framework/TCP \
		$(BUILD_DIR)/System \
		$(BUILD_DIR)/System/Buffers \
		$(BUILD_DIR)/System/Containers \
		$(BUILD_DIR)/System/Events \
		$(BUILD_DIR)/System/IO \
		$(BUILD_DIR)/System/Threading \
		$(BUILD_DIR)/Test \


$(BUILD_DIRS):
	-mkdir -p $@


$(BUILD_DIR): $(BUILD_DIRS)
	-mkdir -p $(BUILD_DIR) \
		$(BIN_DIR) \


