#
# Scalien Makefile for Darwin (OSX)
#

INCLUDE = \
	-I$(KEYSPACE_DIR)/src

LDPATH = \

BASE_CFLAGS = -Wall $(INCLUDE) -DPLATFORM_$(PLATFORM_UCASE) -D__STDC_FORMAT_MACROS
BASE_CXXFLAGS = $(BASE_CFLAGS)
BASE_LDFLAGS = -lpthread -ldb_cxx $(LDPATH)
SOLINK = -Xlinker -x -fPIC -dylib -undefined dynamic_lookup -bundle
SOEXT = dylib
SWIG_LDFLAGS = -bundle -flat_namespace -undefined suppress
BUNDLEEXT = bundle