ALL_OBJECTS = \
	$(BUILD_DIR)/Framework/StorageNew/StorageEnvironment.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageEnvironmentWriter.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageRecovery.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageLogSegment.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageMemoKeyValue.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageFileKeyValue.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageMemoChunk.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageFileChunk.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageChunkSerializer.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageChunkWriter.o \
	$(BUILD_DIR)/Framework/StorageNew/StoragePage.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageHeaderPage.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageDataPage.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageIndexPage.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageBloomPage.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageConfig.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageJob.o \
	$(BUILD_DIR)/Framework/StorageNew/StorageShard.o \
	$(BUILD_DIR)/Framework/StorageNew/StoragePageCache.o \
	$(BUILD_DIR)/Framework/StorageNew/FDGuard.o \
	$(BUILD_DIR)/Framework/BloomFilter.o \
	$(BUILD_DIR)/System/Buffers/Buffer.o \
	$(BUILD_DIR)/System/Buffers/ReadBuffer.o \
	$(BUILD_DIR)/System/Buffers/BufferPool.o \
	$(BUILD_DIR)/System/Events/EventLoop.o \
	$(BUILD_DIR)/System/Events/Scheduler.o \
	$(BUILD_DIR)/System/Events/Timer.o \
	$(BUILD_DIR)/System/Events/Countdown.o \
	$(BUILD_DIR)/System/IO/Endpoint.o \
	$(BUILD_DIR)/System/IO/IOProcessor_Darwin.o \
	$(BUILD_DIR)/System/IO/IOProcessor_Linux.o \
	$(BUILD_DIR)/System/IO/Socket_Posix.o \
	$(BUILD_DIR)/System/Common.o \
	$(BUILD_DIR)/System/Config.o \
	$(BUILD_DIR)/System/Formatting.o \
	$(BUILD_DIR)/System/Log.o \
	$(BUILD_DIR)/System/Stopwatch.o \
	$(BUILD_DIR)/System/ThreadPool_Posix.o \
	$(BUILD_DIR)/System/Time.o \
	$(BUILD_DIR)/System/FileSystem.o

TEST_OBJECTS = \
	$(BUILD_DIR)/Test/Test.o \
	$(BUILD_DIR)/Test/StorageTest.o \
	$(BUILD_DIR)/Test/FileSystemTest.o \
	$(BUILD_DIR)/Test/ArrayListTest.o \
	$(BUILD_DIR)/Test/Timings.o \
	$(BUILD_DIR)/Test/InTreeMapTest.o \
	$(BUILD_DIR)/Test/CrashTest.o 

