CLIENTLIB_OBJECTS = \
	$(BUILD_DIR)/Application/Client/SDBPClient.o \
	$(BUILD_DIR)/Application/Client/SDBPClientRequest.o \
	$(BUILD_DIR)/Application/Client/SDBPClientWrapper.o \
	$(BUILD_DIR)/Application/Client/SDBPControllerConnection.o \
	$(BUILD_DIR)/Application/Client/SDBPShardConnection.o \
	$(BUILD_DIR)/Application/Client/SDBPResult.o \
	$(BUILD_DIR)/Application/Common/ClientRequest.o \
	$(BUILD_DIR)/Application/Common/ClientResponse.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigDatabase.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigQuorum.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigTable.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigShard.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigShardServer.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigController.o \
	$(BUILD_DIR)/Application/ConfigState/ConfigState.o \
	$(BUILD_DIR)/Application/ConfigServer/JSONConfigState.o \
	$(BUILD_DIR)/Application/HTTP/JSONBufferWriter.o \
	$(BUILD_DIR)/Application/SDBP/SDBPRequestMessage.o \
	$(BUILD_DIR)/Application/SDBP/SDBPResponseMessage.o \
	$(BUILD_DIR)/Framework/Messaging/MessageConnection.o \
	$(BUILD_DIR)/Framework/TCP/TCPConnection.o \
	$(BUILD_DIR)/Framework/TCP/TCPWriter.o \
	$(BUILD_DIR)/System/Common.o \
	$(BUILD_DIR)/System/Formatting.o \
	$(BUILD_DIR)/System/Config.o \
	$(BUILD_DIR)/System/Log.o \
	$(BUILD_DIR)/System/Time.o \
	$(BUILD_DIR)/System/Stopwatch.o \
	$(BUILD_DIR)/System/Buffers/Buffer.o \
	$(BUILD_DIR)/System/Buffers/BufferPool.o \
	$(BUILD_DIR)/System/Buffers/ReadBuffer.o \
	$(BUILD_DIR)/System/Events/EventLoop.o \
	$(BUILD_DIR)/System/Events/Scheduler.o \
	$(BUILD_DIR)/System/Events/Countdown.o \
	$(BUILD_DIR)/System/Events/Timer.o \
	$(BUILD_DIR)/System/IO/Endpoint.o \
	$(BUILD_DIR)/System/IO/Socket_Posix.o \
	$(BUILD_DIR)/System/IO/IOProcessor_$(PLATFORM).o \
	$(BUILD_DIR)/System/Threading/ThreadPool_Posix.o \
	$(BUILD_DIR)/System/Threading/Mutex_Posix.o \

SWIG_LIB_OBJECT = \
	$(BUILD_DIR)/Application/Keyspace/Client/KeyspaceClientWrap.o

PYTHON_CLIENT_OBJECT = \
	$(BUILD_DIR)/Application/Keyspace/Client/Python/keyspace_client_python.o
