#
# Scalien Makefile for Darwin (OSX)
#

INCLUDE = \
	-I$(BASE_DIR)/src

LDPATH = \

BASE_CFLAGS = -Wall -W $(INCLUDE) -DPLATFORM_$(PLATFORM_UCASE) -D__STDC_FORMAT_MACROS -pthread
BASE_CXXFLAGS = $(BASE_CFLAGS)
BASE_LDFLAGS = -lpthread $(LDPATH)
SOLINK = -Xlinker -x -fPIC -dylib -undefined dynamic_lookup -bundle
SOEXT = dylib
SWIG_LDFLAGS = -bundle -flat_namespace -undefined suppress
BUNDLEEXT = bundle