#
# Scalien Makefile for Linux
#

INCLUDE = \
	-I$(SCALIENDB_DIR)/src \

LDPATH = \

BASE_CFLAGS = -Wall -W -fPIC $(INCLUDE) -DPLATFORM_$(PLATFORM_UCASE) -D__STDC_FORMAT_MACROS -D_FILE_OFFSET_BITS=64
BASE_CXXFLAGS = $(BASE_CFLAGS)
BASE_LDFLAGS =  -rdynamic -lpthread -lrt $(LDPATH)
SOLINK = -shared -fPIC -Wl,-soname,$(SONAME)
SOEXT = so
SWIG_LDFLAGS = -shared -fPIC 
BUNDLEEXT = so
