#! /bin/sh ##########################################################
#
# scaliendb: replicated, scalable database init script
#
# (C) 2009-2011 Scalien,  http://scalien.com
#
#####################################################################

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="ScalienDB"
RUNSAFE="yes"
DEFAULT=/etc/default/scaliendb

if [ `id -u` != "0" ]
then
  echo "You must be root to start this appication."
  exit 1
fi

test -f $DEFAULT || exit 0
. $DEFAULT

test -x $DAEMON || exit 0

pidof_daemon() {
        pid=`ps auxw | grep "$DAEMON" | grep -v grep | grep -v "$SAFE_DAEMON" | awk '{print $2}'`
}

wait_stop() {
	i=0
	while [ $i -lt $1 ]; do
		pidof_daemon
		if [ "$pid" = "" ]; then
			return
		fi
		sleep 1
		i=`expr $i + 1`
	done
	kill -9 $pid
}

case "$1" in
  start)
	echo -n "Starting $DESC: "
	
	pidof_daemon
	if [ "$pid" != "" ]; then
		echo "$DAEMON is already running!"
		exit 1
	fi

	$SAFE_DAEMON $DAEMON $DEFAULT_CONFIG $DATABASE_DIR
	
	if [ $? -eq 0 ]; then
		echo "$NAME."
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	pidof_daemon
	if [ "$pid" != "" ]; then
    		kill $pid
		pidof_daemon
		if [ "$pid" != "" ]; then
			wait_stop 20
			pidof_daemon
			if [ "$pid" != "" ]; then
				echo "$NAME ($pid) could not be stopped!"
				exit 1
			fi
		fi
		echo "$NAME."
	else
		echo "$NAME is not running."
	fi
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
