@echo off
SET ARCH=%1
SET BUILD_BASE_DIR=%~f2
IF "%BUILD_BASE_DIR%"=="" SET BUILD_BASE_DIR=..\build
SET BIN_DIR=..\bin\%ARCH%
FOR /F %%a IN ('..\script\version.cmd ..\src\Version.h') DO SET VERSION=%%a
SET BUILD_NAME=ScalienDB-%ARCH%-%VERSION%
SET BUILD_ARCH_DIR=%BUILD_BASE_DIR%\%ARCH%\
SET DEBUG_BUILD_DIR="%BUILD_ARCH_DIR%%BUILD_NAME%-Debug"
ECHO Creating build directory: %DEBUG_BUILD_DIR%

IF NOT EXIST %DEBUG_BUILD_DIR% GOTO NODELETEDIR
RMDIR /S /Q %DEBUG_BUILD_DIR%
:NODELETEDIR

MD %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1

COPY %BIN_DIR%\ScalienDB.exe %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1

COPY %BIN_DIR%\ScalienDB.pdb %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1

COPY %BIN_DIR%\scaliendb_client.dll %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1

COPY %BIN_DIR%\scaliendb_client.pdb %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1

COPY %BIN_DIR%\ScalienClient.dll %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1

COPY %BIN_DIR%\ScalienClient.pdb %DEBUG_BUILD_DIR%
IF %ERRORLEVEL% NEQ 0 EXIT /B 1
