@ECHO OFF
SET BASE_DIR=%1
SET TARGET_DIR=%2
SET TARGET_NAME=%3
ECHO Copying DLL to Win32 release path
COPY %TARGET_DIR%\%TARGET_NAME%.dll %BASE_DIR%\bin\Win32
COPY %TARGET_DIR%\%TARGET_NAME%.pdb %BASE_DIR%\bin\Win32
ECHO Copying DLL to x64 release path
COPY %TARGET_DIR%\%TARGET_NAME%.dll %BASE_DIR%\bin\x64
COPY %TARGET_DIR%\%TARGET_NAME%.pdb %BASE_DIR%\bin\x64
