@echo off
set FILENAME=%1

SETLOCAL ENABLEEXTENSIONS
FOR /F "tokens=3" %%a IN (
'FINDSTR /C:"#define VERSION_MAJOR" %FILENAME%'
) DO (
SET VERSION_MAJOR=%%~a
) 
FOR /F "tokens=3" %%a IN (
'FINDSTR /C:"#define VERSION_MINOR" %FILENAME%'
) DO (
SET VERSION_MINOR=%%~a
) 
FOR /F "tokens=3" %%a IN (
'FINDSTR /C:"#define VERSION_RELEASE" %FILENAME%'
) DO (
SET VERSION_RELEASE=%%~a
) 

echo %VERSION_MAJOR%.%VERSION_MINOR%.%VERSION_RELEASE%