@ECHO OFF
SET BUILD_DIR=%~dp1
SET BUILD_NAME=%2
SET ZIPFILE=%BUILD_DIR%%BUILD_NAME%.zip
ECHO.
ECHO Creating zipfile %ZIPFILE%
ECHO.
CSCRIPT //Nologo ..\script\zipfolder.vbs %BUILD_DIR%%BUILD_NAME% %ZIPFILE%