# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_scaliendb_client', [dirname(__file__)])
        except ImportError:
            import _scaliendb_client
            return _scaliendb_client
        if fp is not None:
            try:
                _mod = imp.load_module('_scaliendb_client', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _scaliendb_client = swig_import_helper()
    del swig_import_helper
else:
    import _scaliendb_client
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _scaliendb_client.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _scaliendb_client.SwigPyIterator_value(self)
    def incr(self, n = 1): return _scaliendb_client.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _scaliendb_client.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _scaliendb_client.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _scaliendb_client.SwigPyIterator_equal(self, *args)
    def copy(self): return _scaliendb_client.SwigPyIterator_copy(self)
    def next(self): return _scaliendb_client.SwigPyIterator_next(self)
    def __next__(self): return _scaliendb_client.SwigPyIterator___next__(self)
    def previous(self): return _scaliendb_client.SwigPyIterator_previous(self)
    def advance(self, *args): return _scaliendb_client.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _scaliendb_client.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _scaliendb_client.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _scaliendb_client.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _scaliendb_client.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _scaliendb_client.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _scaliendb_client.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _scaliendb_client.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class imaxdiv_t(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    quot = _swig_property(_scaliendb_client.imaxdiv_t_quot_get, _scaliendb_client.imaxdiv_t_quot_set)
    rem = _swig_property(_scaliendb_client.imaxdiv_t_rem_get, _scaliendb_client.imaxdiv_t_rem_set)
    def __init__(self): 
        this = _scaliendb_client.new_imaxdiv_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scaliendb_client.delete_imaxdiv_t
    __del__ = lambda self : None;
imaxdiv_t_swigregister = _scaliendb_client.imaxdiv_t_swigregister
imaxdiv_t_swigregister(imaxdiv_t)


def imaxabs(*args):
  return _scaliendb_client.imaxabs(*args)
imaxabs = _scaliendb_client.imaxabs

def imaxdiv(*args):
  return _scaliendb_client.imaxdiv(*args)
imaxdiv = _scaliendb_client.imaxdiv

def strtoimax(*args):
  return _scaliendb_client.strtoimax(*args)
strtoimax = _scaliendb_client.strtoimax

def strtoumax(*args):
  return _scaliendb_client.strtoumax(*args)
strtoumax = _scaliendb_client.strtoumax

def wcstoimax(*args):
  return _scaliendb_client.wcstoimax(*args)
wcstoimax = _scaliendb_client.wcstoimax

def wcstoumax(*args):
  return _scaliendb_client.wcstoumax(*args)
wcstoumax = _scaliendb_client.wcstoumax
class SDBP_NodeParams(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _scaliendb_client.new_SDBP_NodeParams(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _scaliendb_client.delete_SDBP_NodeParams
    __del__ = lambda self : None;
    def Close(self): return _scaliendb_client.SDBP_NodeParams_Close(self)
    def AddNode(self, *args): return _scaliendb_client.SDBP_NodeParams_AddNode(self, *args)
    nodec = _swig_property(_scaliendb_client.SDBP_NodeParams_nodec_get, _scaliendb_client.SDBP_NodeParams_nodec_set)
    nodes = _swig_property(_scaliendb_client.SDBP_NodeParams_nodes_get, _scaliendb_client.SDBP_NodeParams_nodes_set)
    num = _swig_property(_scaliendb_client.SDBP_NodeParams_num_get, _scaliendb_client.SDBP_NodeParams_num_set)
SDBP_NodeParams_swigregister = _scaliendb_client.SDBP_NodeParams_swigregister
SDBP_NodeParams_swigregister(SDBP_NodeParams)

class SDBP_Buffer(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self): 
        this = _scaliendb_client.new_SDBP_Buffer()
        try: self.this.append(this)
        except: self.this = this
    def SetBuffer(self, *args): return _scaliendb_client.SDBP_Buffer_SetBuffer(self, *args)
    data = _swig_property(_scaliendb_client.SDBP_Buffer_data_get, _scaliendb_client.SDBP_Buffer_data_set)
    len = _swig_property(_scaliendb_client.SDBP_Buffer_len_get, _scaliendb_client.SDBP_Buffer_len_set)
    __swig_destroy__ = _scaliendb_client.delete_SDBP_Buffer
    __del__ = lambda self : None;
SDBP_Buffer_swigregister = _scaliendb_client.SDBP_Buffer_swigregister
SDBP_Buffer_swigregister(SDBP_Buffer)


def SDBP_ResultClose(*args):
  return _scaliendb_client.SDBP_ResultClose(*args)
SDBP_ResultClose = _scaliendb_client.SDBP_ResultClose

def SDBP_ResultKey(*args):
  return _scaliendb_client.SDBP_ResultKey(*args)
SDBP_ResultKey = _scaliendb_client.SDBP_ResultKey

def SDBP_ResultValue(*args):
  return _scaliendb_client.SDBP_ResultValue(*args)
SDBP_ResultValue = _scaliendb_client.SDBP_ResultValue

def SDBP_ResultKeyBuffer(*args):
  return _scaliendb_client.SDBP_ResultKeyBuffer(*args)
SDBP_ResultKeyBuffer = _scaliendb_client.SDBP_ResultKeyBuffer

def SDBP_ResultValueBuffer(*args):
  return _scaliendb_client.SDBP_ResultValueBuffer(*args)
SDBP_ResultValueBuffer = _scaliendb_client.SDBP_ResultValueBuffer

def SDBP_ResultSignedNumber(*args):
  return _scaliendb_client.SDBP_ResultSignedNumber(*args)
SDBP_ResultSignedNumber = _scaliendb_client.SDBP_ResultSignedNumber

def SDBP_ResultNumber(*args):
  return _scaliendb_client.SDBP_ResultNumber(*args)
SDBP_ResultNumber = _scaliendb_client.SDBP_ResultNumber

def SDBP_ResultIsConditionalSuccess(*args):
  return _scaliendb_client.SDBP_ResultIsConditionalSuccess(*args)
SDBP_ResultIsConditionalSuccess = _scaliendb_client.SDBP_ResultIsConditionalSuccess

def SDBP_ResultDatabaseID(*args):
  return _scaliendb_client.SDBP_ResultDatabaseID(*args)
SDBP_ResultDatabaseID = _scaliendb_client.SDBP_ResultDatabaseID

def SDBP_ResultTableID(*args):
  return _scaliendb_client.SDBP_ResultTableID(*args)
SDBP_ResultTableID = _scaliendb_client.SDBP_ResultTableID

def SDBP_ResultBegin(*args):
  return _scaliendb_client.SDBP_ResultBegin(*args)
SDBP_ResultBegin = _scaliendb_client.SDBP_ResultBegin

def SDBP_ResultNext(*args):
  return _scaliendb_client.SDBP_ResultNext(*args)
SDBP_ResultNext = _scaliendb_client.SDBP_ResultNext

def SDBP_ResultIsEnd(*args):
  return _scaliendb_client.SDBP_ResultIsEnd(*args)
SDBP_ResultIsEnd = _scaliendb_client.SDBP_ResultIsEnd

def SDBP_ResultIsFinished(*args):
  return _scaliendb_client.SDBP_ResultIsFinished(*args)
SDBP_ResultIsFinished = _scaliendb_client.SDBP_ResultIsFinished

def SDBP_ResultTransportStatus(*args):
  return _scaliendb_client.SDBP_ResultTransportStatus(*args)
SDBP_ResultTransportStatus = _scaliendb_client.SDBP_ResultTransportStatus

def SDBP_ResultCommandStatus(*args):
  return _scaliendb_client.SDBP_ResultCommandStatus(*args)
SDBP_ResultCommandStatus = _scaliendb_client.SDBP_ResultCommandStatus

def SDBP_ResultNumNodes(*args):
  return _scaliendb_client.SDBP_ResultNumNodes(*args)
SDBP_ResultNumNodes = _scaliendb_client.SDBP_ResultNumNodes

def SDBP_ResultNodeID(*args):
  return _scaliendb_client.SDBP_ResultNodeID(*args)
SDBP_ResultNodeID = _scaliendb_client.SDBP_ResultNodeID

def SDBP_ResultElapsedTime(*args):
  return _scaliendb_client.SDBP_ResultElapsedTime(*args)
SDBP_ResultElapsedTime = _scaliendb_client.SDBP_ResultElapsedTime

def SDBP_Create():
  return _scaliendb_client.SDBP_Create()
SDBP_Create = _scaliendb_client.SDBP_Create

def SDBP_Init(*args):
  return _scaliendb_client.SDBP_Init(*args)
SDBP_Init = _scaliendb_client.SDBP_Init

def SDBP_Destroy(*args):
  return _scaliendb_client.SDBP_Destroy(*args)
SDBP_Destroy = _scaliendb_client.SDBP_Destroy

def SDBP_GetResult(*args):
  return _scaliendb_client.SDBP_GetResult(*args)
SDBP_GetResult = _scaliendb_client.SDBP_GetResult

def SDBP_SetGlobalTimeout(*args):
  return _scaliendb_client.SDBP_SetGlobalTimeout(*args)
SDBP_SetGlobalTimeout = _scaliendb_client.SDBP_SetGlobalTimeout

def SDBP_SetMasterTimeout(*args):
  return _scaliendb_client.SDBP_SetMasterTimeout(*args)
SDBP_SetMasterTimeout = _scaliendb_client.SDBP_SetMasterTimeout

def SDBP_GetGlobalTimeout(*args):
  return _scaliendb_client.SDBP_GetGlobalTimeout(*args)
SDBP_GetGlobalTimeout = _scaliendb_client.SDBP_GetGlobalTimeout

def SDBP_GetMasterTimeout(*args):
  return _scaliendb_client.SDBP_GetMasterTimeout(*args)
SDBP_GetMasterTimeout = _scaliendb_client.SDBP_GetMasterTimeout

def SDBP_GetJSONConfigState(*args):
  return _scaliendb_client.SDBP_GetJSONConfigState(*args)
SDBP_GetJSONConfigState = _scaliendb_client.SDBP_GetJSONConfigState

def SDBP_WaitConfigState(*args):
  return _scaliendb_client.SDBP_WaitConfigState(*args)
SDBP_WaitConfigState = _scaliendb_client.SDBP_WaitConfigState

def SDBP_SetConsistencyMode(*args):
  return _scaliendb_client.SDBP_SetConsistencyMode(*args)
SDBP_SetConsistencyMode = _scaliendb_client.SDBP_SetConsistencyMode

def SDBP_SetBatchMode(*args):
  return _scaliendb_client.SDBP_SetBatchMode(*args)
SDBP_SetBatchMode = _scaliendb_client.SDBP_SetBatchMode

def SDBP_SetBatchLimit(*args):
  return _scaliendb_client.SDBP_SetBatchLimit(*args)
SDBP_SetBatchLimit = _scaliendb_client.SDBP_SetBatchLimit

def SDBP_CreateDatabase(*args):
  return _scaliendb_client.SDBP_CreateDatabase(*args)
SDBP_CreateDatabase = _scaliendb_client.SDBP_CreateDatabase

def SDBP_RenameDatabase(*args):
  return _scaliendb_client.SDBP_RenameDatabase(*args)
SDBP_RenameDatabase = _scaliendb_client.SDBP_RenameDatabase

def SDBP_DeleteDatabase(*args):
  return _scaliendb_client.SDBP_DeleteDatabase(*args)
SDBP_DeleteDatabase = _scaliendb_client.SDBP_DeleteDatabase

def SDBP_CreateTable(*args):
  return _scaliendb_client.SDBP_CreateTable(*args)
SDBP_CreateTable = _scaliendb_client.SDBP_CreateTable

def SDBP_RenameTable(*args):
  return _scaliendb_client.SDBP_RenameTable(*args)
SDBP_RenameTable = _scaliendb_client.SDBP_RenameTable

def SDBP_DeleteTable(*args):
  return _scaliendb_client.SDBP_DeleteTable(*args)
SDBP_DeleteTable = _scaliendb_client.SDBP_DeleteTable

def SDBP_TruncateTable(*args):
  return _scaliendb_client.SDBP_TruncateTable(*args)
SDBP_TruncateTable = _scaliendb_client.SDBP_TruncateTable

def SDBP_GetNumQuorums(*args):
  return _scaliendb_client.SDBP_GetNumQuorums(*args)
SDBP_GetNumQuorums = _scaliendb_client.SDBP_GetNumQuorums

def SDBP_GetQuorumIDAt(*args):
  return _scaliendb_client.SDBP_GetQuorumIDAt(*args)
SDBP_GetQuorumIDAt = _scaliendb_client.SDBP_GetQuorumIDAt

def SDBP_GetQuorumNameAt(*args):
  return _scaliendb_client.SDBP_GetQuorumNameAt(*args)
SDBP_GetQuorumNameAt = _scaliendb_client.SDBP_GetQuorumNameAt

def SDBP_GetQuorumIDByName(*args):
  return _scaliendb_client.SDBP_GetQuorumIDByName(*args)
SDBP_GetQuorumIDByName = _scaliendb_client.SDBP_GetQuorumIDByName

def SDBP_GetNumDatabases(*args):
  return _scaliendb_client.SDBP_GetNumDatabases(*args)
SDBP_GetNumDatabases = _scaliendb_client.SDBP_GetNumDatabases

def SDBP_GetDatabaseIDAt(*args):
  return _scaliendb_client.SDBP_GetDatabaseIDAt(*args)
SDBP_GetDatabaseIDAt = _scaliendb_client.SDBP_GetDatabaseIDAt

def SDBP_GetDatabaseNameAt(*args):
  return _scaliendb_client.SDBP_GetDatabaseNameAt(*args)
SDBP_GetDatabaseNameAt = _scaliendb_client.SDBP_GetDatabaseNameAt

def SDBP_GetDatabaseIDByName(*args):
  return _scaliendb_client.SDBP_GetDatabaseIDByName(*args)
SDBP_GetDatabaseIDByName = _scaliendb_client.SDBP_GetDatabaseIDByName

def SDBP_GetNumTables(*args):
  return _scaliendb_client.SDBP_GetNumTables(*args)
SDBP_GetNumTables = _scaliendb_client.SDBP_GetNumTables

def SDBP_GetTableIDAt(*args):
  return _scaliendb_client.SDBP_GetTableIDAt(*args)
SDBP_GetTableIDAt = _scaliendb_client.SDBP_GetTableIDAt

def SDBP_GetTableNameAt(*args):
  return _scaliendb_client.SDBP_GetTableNameAt(*args)
SDBP_GetTableNameAt = _scaliendb_client.SDBP_GetTableNameAt

def SDBP_GetTableIDByName(*args):
  return _scaliendb_client.SDBP_GetTableIDByName(*args)
SDBP_GetTableIDByName = _scaliendb_client.SDBP_GetTableIDByName

def SDBP_Get(*args):
  return _scaliendb_client.SDBP_Get(*args)
SDBP_Get = _scaliendb_client.SDBP_Get

def SDBP_GetCStr(*args):
  return _scaliendb_client.SDBP_GetCStr(*args)
SDBP_GetCStr = _scaliendb_client.SDBP_GetCStr

def SDBP_Set(*args):
  return _scaliendb_client.SDBP_Set(*args)
SDBP_Set = _scaliendb_client.SDBP_Set

def SDBP_SetCStr(*args):
  return _scaliendb_client.SDBP_SetCStr(*args)
SDBP_SetCStr = _scaliendb_client.SDBP_SetCStr

def SDBP_Add(*args):
  return _scaliendb_client.SDBP_Add(*args)
SDBP_Add = _scaliendb_client.SDBP_Add

def SDBP_AddCStr(*args):
  return _scaliendb_client.SDBP_AddCStr(*args)
SDBP_AddCStr = _scaliendb_client.SDBP_AddCStr

def SDBP_Delete(*args):
  return _scaliendb_client.SDBP_Delete(*args)
SDBP_Delete = _scaliendb_client.SDBP_Delete

def SDBP_DeleteCStr(*args):
  return _scaliendb_client.SDBP_DeleteCStr(*args)
SDBP_DeleteCStr = _scaliendb_client.SDBP_DeleteCStr

def SDBP_SequenceSet(*args):
  return _scaliendb_client.SDBP_SequenceSet(*args)
SDBP_SequenceSet = _scaliendb_client.SDBP_SequenceSet

def SDBP_SequenceSetCStr(*args):
  return _scaliendb_client.SDBP_SequenceSetCStr(*args)
SDBP_SequenceSetCStr = _scaliendb_client.SDBP_SequenceSetCStr

def SDBP_SequenceNext(*args):
  return _scaliendb_client.SDBP_SequenceNext(*args)
SDBP_SequenceNext = _scaliendb_client.SDBP_SequenceNext

def SDBP_SequenceNextCStr(*args):
  return _scaliendb_client.SDBP_SequenceNextCStr(*args)
SDBP_SequenceNextCStr = _scaliendb_client.SDBP_SequenceNextCStr

def SDBP_ListKeys(*args):
  return _scaliendb_client.SDBP_ListKeys(*args)
SDBP_ListKeys = _scaliendb_client.SDBP_ListKeys

def SDBP_ListKeysCStr(*args):
  return _scaliendb_client.SDBP_ListKeysCStr(*args)
SDBP_ListKeysCStr = _scaliendb_client.SDBP_ListKeysCStr

def SDBP_ListKeyValues(*args):
  return _scaliendb_client.SDBP_ListKeyValues(*args)
SDBP_ListKeyValues = _scaliendb_client.SDBP_ListKeyValues

def SDBP_ListKeyValuesCStr(*args):
  return _scaliendb_client.SDBP_ListKeyValuesCStr(*args)
SDBP_ListKeyValuesCStr = _scaliendb_client.SDBP_ListKeyValuesCStr

def SDBP_Count(*args):
  return _scaliendb_client.SDBP_Count(*args)
SDBP_Count = _scaliendb_client.SDBP_Count

def SDBP_CountCStr(*args):
  return _scaliendb_client.SDBP_CountCStr(*args)
SDBP_CountCStr = _scaliendb_client.SDBP_CountCStr

def SDBP_Begin(*args):
  return _scaliendb_client.SDBP_Begin(*args)
SDBP_Begin = _scaliendb_client.SDBP_Begin

def SDBP_Submit(*args):
  return _scaliendb_client.SDBP_Submit(*args)
SDBP_Submit = _scaliendb_client.SDBP_Submit

def SDBP_Cancel(*args):
  return _scaliendb_client.SDBP_Cancel(*args)
SDBP_Cancel = _scaliendb_client.SDBP_Cancel

def SDBP_SetTrace(*args):
  return _scaliendb_client.SDBP_SetTrace(*args)
SDBP_SetTrace = _scaliendb_client.SDBP_SetTrace

def SDBP_SetLogFile(*args):
  return _scaliendb_client.SDBP_SetLogFile(*args)
SDBP_SetLogFile = _scaliendb_client.SDBP_SetLogFile

def SDBP_GetVersion():
  return _scaliendb_client.SDBP_GetVersion()
SDBP_GetVersion = _scaliendb_client.SDBP_GetVersion

def SDBP_GetDebugString():
  return _scaliendb_client.SDBP_GetDebugString()
SDBP_GetDebugString = _scaliendb_client.SDBP_GetDebugString

def SDBP_LogTrace(*args):
  return _scaliendb_client.SDBP_LogTrace(*args)
SDBP_LogTrace = _scaliendb_client.SDBP_LogTrace


