/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.scalien.scaliendb;

public class scaliendb_client {
  public static long imaxabs(long n) {
    return scaliendb_clientJNI.imaxabs(n);
  }

  public static imaxdiv_t imaxdiv(long numer, long denom) {
    return new imaxdiv_t(scaliendb_clientJNI.imaxdiv(numer, denom), true);
  }

  public static long strtoimax(String nptr, SWIGTYPE_p_p_char endptr, int base) {
    return scaliendb_clientJNI.strtoimax(nptr, SWIGTYPE_p_p_char.getCPtr(endptr), base);
  }

  public static java.math.BigInteger strtoumax(String nptr, SWIGTYPE_p_p_char endptr, int base) {
    return scaliendb_clientJNI.strtoumax(nptr, SWIGTYPE_p_p_char.getCPtr(endptr), base);
  }

  public static void SDBP_ResultClose(SWIGTYPE_p_void result) {
    scaliendb_clientJNI.SDBP_ResultClose(SWIGTYPE_p_void.getCPtr(result));
  }

  public static String SDBP_ResultKey(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultKey(SWIGTYPE_p_void.getCPtr(result));
  }

  public static String SDBP_ResultValue(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultValue(SWIGTYPE_p_void.getCPtr(result));
  }

  public static java.math.BigInteger SDBP_ResultDatabaseID(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultDatabaseID(SWIGTYPE_p_void.getCPtr(result));
  }

  public static java.math.BigInteger SDBP_ResultTableID(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultTableID(SWIGTYPE_p_void.getCPtr(result));
  }

  public static void SDBP_ResultBegin(SWIGTYPE_p_void result) {
    scaliendb_clientJNI.SDBP_ResultBegin(SWIGTYPE_p_void.getCPtr(result));
  }

  public static void SDBP_ResultNext(SWIGTYPE_p_void result) {
    scaliendb_clientJNI.SDBP_ResultNext(SWIGTYPE_p_void.getCPtr(result));
  }

  public static boolean SDBP_ResultIsEnd(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultIsEnd(SWIGTYPE_p_void.getCPtr(result));
  }

  public static int SDBP_ResultTransportStatus(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultTransportStatus(SWIGTYPE_p_void.getCPtr(result));
  }

  public static int SDBP_ResultCommandStatus(SWIGTYPE_p_void result) {
    return scaliendb_clientJNI.SDBP_ResultCommandStatus(SWIGTYPE_p_void.getCPtr(result));
  }

  public static SWIGTYPE_p_void SDBP_Create() {
    long cPtr = scaliendb_clientJNI.SDBP_Create();
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static int SDBP_Init(SWIGTYPE_p_void client, SDBP_NodeParams params) {
    return scaliendb_clientJNI.SDBP_Init(SWIGTYPE_p_void.getCPtr(client), SDBP_NodeParams.getCPtr(params), params);
  }

  public static void SDBP_Destroy(SWIGTYPE_p_void client) {
    scaliendb_clientJNI.SDBP_Destroy(SWIGTYPE_p_void.getCPtr(client));
  }

  public static SWIGTYPE_p_void SDBP_GetResult(SWIGTYPE_p_void client) {
    long cPtr = scaliendb_clientJNI.SDBP_GetResult(SWIGTYPE_p_void.getCPtr(client));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static void SDBP_SetGlobalTimeout(SWIGTYPE_p_void client, java.math.BigInteger timeout) {
    scaliendb_clientJNI.SDBP_SetGlobalTimeout(SWIGTYPE_p_void.getCPtr(client), timeout);
  }

  public static void SDBP_SetMasterTimeout(SWIGTYPE_p_void client, java.math.BigInteger timeout) {
    scaliendb_clientJNI.SDBP_SetMasterTimeout(SWIGTYPE_p_void.getCPtr(client), timeout);
  }

  public static java.math.BigInteger SDBP_GetGlobalTimeout(SWIGTYPE_p_void client) {
    return scaliendb_clientJNI.SDBP_GetGlobalTimeout(SWIGTYPE_p_void.getCPtr(client));
  }

  public static java.math.BigInteger SDBP_GetMasterTimeout(SWIGTYPE_p_void client) {
    return scaliendb_clientJNI.SDBP_GetMasterTimeout(SWIGTYPE_p_void.getCPtr(client));
  }

  public static java.math.BigInteger SDBP_GetDatabaseID(SWIGTYPE_p_void client, String name) {
    return scaliendb_clientJNI.SDBP_GetDatabaseID(SWIGTYPE_p_void.getCPtr(client), name);
  }

  public static java.math.BigInteger SDBP_GetTableID(SWIGTYPE_p_void client, java.math.BigInteger databaseID, String name) {
    return scaliendb_clientJNI.SDBP_GetTableID(SWIGTYPE_p_void.getCPtr(client), databaseID, name);
  }

  public static int SDBP_UseDatabase(SWIGTYPE_p_void client, String name) {
    return scaliendb_clientJNI.SDBP_UseDatabase(SWIGTYPE_p_void.getCPtr(client), name);
  }

  public static int SDBP_UseTable(SWIGTYPE_p_void client, String name) {
    return scaliendb_clientJNI.SDBP_UseTable(SWIGTYPE_p_void.getCPtr(client), name);
  }

  public static int SDBP_Get(SWIGTYPE_p_void client, String key) {
    return scaliendb_clientJNI.SDBP_Get(SWIGTYPE_p_void.getCPtr(client), key);
  }

  public static int SDBP_Set(SWIGTYPE_p_void client, String key, String value) {
    return scaliendb_clientJNI.SDBP_Set(SWIGTYPE_p_void.getCPtr(client), key, value);
  }

  public static int SDBP_Delete(SWIGTYPE_p_void client, String key) {
    return scaliendb_clientJNI.SDBP_Delete(SWIGTYPE_p_void.getCPtr(client), key);
  }

  public static boolean SDBP_IsBatched(SWIGTYPE_p_void client) {
    return scaliendb_clientJNI.SDBP_IsBatched(SWIGTYPE_p_void.getCPtr(client));
  }

  public static void SDBP_SetTrace(boolean trace) {
    scaliendb_clientJNI.SDBP_SetTrace(trace);
  }

}
