/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.scalien.scaliendb;

public class SDBP_Buffer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SDBP_Buffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SDBP_Buffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      scaliendb_clientJNI.delete_SDBP_Buffer(swigCPtr);
    }
    swigCPtr = 0;
  }

  public SDBP_Buffer() {
    this(scaliendb_clientJNI.new_SDBP_Buffer(), true);
  }

  public void SetBuffer(byte[] data_, int len_) {
    scaliendb_clientJNI.SDBP_Buffer_SetBuffer(swigCPtr, this, data_, len_);
  }

  public void setData(int value) {
    scaliendb_clientJNI.SDBP_Buffer_data_set(swigCPtr, this, value);
  }

  public int getData() {
    return scaliendb_clientJNI.SDBP_Buffer_data_get(swigCPtr, this);
  }

  public void setLen(int value) {
    scaliendb_clientJNI.SDBP_Buffer_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return scaliendb_clientJNI.SDBP_Buffer_len_get(swigCPtr, this);
  }

}
