/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Scalien {

using System;
using System.Runtime.InteropServices;

public class SDBP_NodeParams : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SDBP_NodeParams(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SDBP_NodeParams obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SDBP_NodeParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          scaliendb_clientPINVOKE.delete_SDBP_NodeParams(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public unsafe SDBP_NodeParams(int nodec_) : this(scaliendb_clientPINVOKE.new_SDBP_NodeParams(nodec_), true) {
  }

  public unsafe void Close() {
    scaliendb_clientPINVOKE.SDBP_NodeParams_Close(swigCPtr);
  }

  public unsafe void AddNode(string node) {
    scaliendb_clientPINVOKE.SDBP_NodeParams_AddNode(swigCPtr, node);
    if (scaliendb_clientPINVOKE.SWIGPendingException.Pending) throw scaliendb_clientPINVOKE.SWIGPendingException.Retrieve();
  }

  public unsafe int nodec {
    set {
      scaliendb_clientPINVOKE.SDBP_NodeParams_nodec_set(swigCPtr, value);
    } 
    get {
      int ret = scaliendb_clientPINVOKE.SDBP_NodeParams_nodec_get(swigCPtr);
      return ret;
    } 
  }

  public unsafe SWIGTYPE_p_p_char nodes {
    set {
      scaliendb_clientPINVOKE.SDBP_NodeParams_nodes_set(swigCPtr, SWIGTYPE_p_p_char.getCPtr(value));
    } 
    get {
      IntPtr cPtr = scaliendb_clientPINVOKE.SDBP_NodeParams_nodes_get(swigCPtr);
      SWIGTYPE_p_p_char ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
      return ret;
    } 
  }

  public unsafe int num {
    set {
      scaliendb_clientPINVOKE.SDBP_NodeParams_num_set(swigCPtr, value);
    } 
    get {
      int ret = scaliendb_clientPINVOKE.SDBP_NodeParams_num_get(swigCPtr);
      return ret;
    } 
  }

}

}
