/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Scalien {

using System;
using System.Runtime.InteropServices;

public class SDBP_Buffer : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SDBP_Buffer(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(SDBP_Buffer obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~SDBP_Buffer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
        swigCMemOwn = false;
        scaliendb_clientPINVOKE.delete_SDBP_Buffer(swigCPtr);
      }
      swigCPtr = new HandleRef(null, IntPtr.Zero);
      GC.SuppressFinalize(this);
    }
  }

  public SDBP_Buffer() : this(scaliendb_clientPINVOKE.new_SDBP_Buffer(), true) {
  }

  public void SetBuffer(byte[] data_, int len_) {
    scaliendb_clientPINVOKE.SDBP_Buffer_SetBuffer(swigCPtr, data_, len_);
  }

  public SWIGTYPE_p_void data {
    set {
      scaliendb_clientPINVOKE.SDBP_Buffer_data_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      IntPtr cPtr = scaliendb_clientPINVOKE.SDBP_Buffer_data_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public int len {
    set {
      scaliendb_clientPINVOKE.SDBP_Buffer_len_set(swigCPtr, value);
    } 
    get {
      int ret = scaliendb_clientPINVOKE.SDBP_Buffer_len_get(swigCPtr);
      return ret;
    } 
  }

}

}
